on:
  pull_request:
    branches:
      - main

jobs:
  ESLint:
    name: ESLint-verify
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.15'
          
      - name: Checkout 
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: npm install

      - name: Run Eslint
        run: npm run lint
